logging:
  level:
    org:
      hibernate:
        type: trace
    study:
      testproject: trace
      
server:
  port: 8081
  
spring:
  config:
    activate: 
      on-profile: local  
#  datasource:
#    url: jdbc:postgresql://localhost:5432/etl?options=-c%20search_path=project
#    username: postgres
#    password: 1234
  datasource:
    url: jdbc:h2:~/project
    username: sa
    password:    
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false
  devtools.livereload.enabled: true
  security:
    user:
      name: user
      password: 1234

---
logging:
  level:
    org:
      hibernate:
        type: trace
    study:
      testproject: trace
      
server:
  port: 8081
  
spring:
  config:
    activate: 
      on-profile: test  
#  datasource:
#    url: jdbc:postgresql://localhost:5432/etl?options=-c%20search_path=projecttest
#    username: postgres
#    password: 1234
  datasource:
    url: jdbc:h2:~/project_test
    username: sa
    password:        
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    properties.hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console 
  thymeleaf:
    cache: false
  devtools.livereload.enabled: true
  
  security:
    user:
      name: user
      password: 1234
